=== Team302/2026Rebuilt/src/main/deploy/auton/auton.dtd
<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive (zone* ) >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | 
                              TRAJECTORY_DRIVE | RESET_POSITION | RESET_POSITION_NO_VISION | DRIVE_STOP_MECH) "DO_NOTHING"
		  pathUpdateOption 	( NOTHING) "NOTHING"
		  time				CDATA #IMPLIED
		  delayOption		(START ) "START"
          headingOption     CDATA "IGNORE"
          heading           CDATA "0.0"
		  choreoname		CDATA #IMPLIED
		  visionAligment    ( UNKNOWN ) "UNKNOWN"
		  launcherState		( STATE_OFF | STATE_INITIALIZE | STATE_IDLE | STATE_PREPARE_TO_LAUNCH ) "STATE_IDLE"
		  intakeState		( STATE_OFF | STATE_INTAKE | STATE_EXPEL ) "STATE_OFF"
		  climberState		( STATE_OFF | STATE_WANT_TO_CLIMB ) "STATE_OFF"
>


<!ELEMENT zone EMPTY >
<!ATTLIST zone
		filename CDATA #REQUIRED
		
>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedRLaunch0DepOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "DRIVE_STOP_MECH"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_A"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_B"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_C"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH">
<zone filename = "RedClimbingZone.xml"/>
</primitive>
<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>
